name: Testing Conditions

on:
  push:
    branches:
    - master

jobs:
  build_and_deploy_job:
    if: ${{ secrets.SOME_SUPER_SECRET != "" }}
    runs-on: ubuntu-latest
    name: Build
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201

    - name: Build App
      run: dotnet build -c Release